name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"  # Версия Python для вашей программы

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install kivy buildozer cython

    - name: Install Xcode Tools
      run: |
        brew install --cask xcode
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -license accept

    - name: Prepare Buildozer
      run: |
        python -m pip install buildozer
        buildozer init  # Генерация файла buildozer.spec

    - name: Configure buildozer.spec
      run: |
        sed -i '' 's/^#?ios.kivy_ios_url = .*/ios.kivy_ios_url = https:\/\/github.com\/kivy\/kivy-ios.git/' buildozer.spec
        sed -i '' 's/^#?ios.kivy_ios_branch = .*/ios.kivy_ios_branch = master/' buildozer.spec
        sed -i '' 's/^#?title = .*/title = Vismon App/' buildozer.spec
        sed -i '' 's/^#?package.name = .*/package.name = vismon/' buildozer.spec
        sed -i '' 's/^#?package.domain = .*/package.domain = com.example/' buildozer.spec
        sed -i '' 's/^#?source.include_exts = .*/source.include_exts = py,png,jpg,kv,atlas/' buildozer.spec

    - name: Build iOS App
      run: |
        buildozer -v ios debug

    - name: Archive .ipa file
      uses: actions/upload-artifact@v3
      with:
        name: vismon-ios-app
        path: bin/ios/*debug.ipa
